version: '2.1'

services:
  web:
    build: .
    volumes:
      - .:/code
    command:
      bash -c "python3 shopping/manage.py migrate &&
      python3 shopping/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: 'service_healthy'
    restart: on-failure
  db:
    image: postgres
    environment:
    - POSTGRES_DB=shopdb
    - POSTGRES_USER=shopuser
    - POSTGRES_PASSWORD=shoppass
    healthcheck:
      test: "PGPASSWORD=shoppass psql -h localhost -d shopdb -U shopuser -c '\\l'"
      interval: 5s
      timeout: 6s
      retries: 10
    ports:
    - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: